# Generated by Django 2.0 on 2018-07-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('cluster_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('citations', models.IntegerField()),
                ('versions', models.IntegerField()),
                ('citations_url', models.CharField(max_length=100)),
                ('versions_url', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_id', to='api_server.Article')),
                ('cited_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_id', to='api_server.Article')),
            ],
        ),
    ]
