# Generated by Django 2.0 on 2018-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='article',
            name='citations_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='article',
            name='versions_url',
        ),
        migrations.AddField(
            model_name='article',
            name='num_citations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='num_versions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='url_citations',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='url_versions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
