# Generated by Django 2.0 on 2018-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20180715_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatus',
            name='citation_expansioin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='expansioin_depth',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='importance',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
