# Generated by Django 2.0 on 2018-07-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_auto_20180715_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='api_server.Article'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='cited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_set', to='api_server.Article'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='citing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citing_set', to='api_server.Article'),
        ),
    ]
