# Generated by Django 2.0 on 2018-07-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0006_auto_20180716_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlestatus',
            old_name='expansioin_depth',
            new_name='expansion_depth',
        ),
    ]
