# Generated by Django 2.0 on 2018-07-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0007_auto_20180716_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatus',
            name='citation_expansioin',
        ),
        migrations.AddField(
            model_name='articlestatus',
            name='citations_expansioin',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
