# Generated by Django 2.0 on 2018-07-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0008_auto_20180716_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlestatus',
            old_name='citations_expansioin',
            new_name='citations_expansion',
        ),
    ]
