# Generated by Django 2.0 on 2018-07-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0009_auto_20180716_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.IntegerField(db_index=True, default=-1, null=True),
        ),
    ]
