# Generated by Django 2.0 on 2018-07-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0010_auto_20180716_0204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('citing', 'cited')},
        ),
    ]
